begin;

create extension if not exists pgcrypto;

create table if not exists public.staff_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'staff' check (role in ('staff','manager','admin','owner')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.points_transactions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete restrict,
  points_delta bigint not null check (points_delta <> 0),
  balance_after bigint not null check (balance_after >= 0),
  transaction_type text not null check (transaction_type in ('award','redeem','adjustment','welcome','refund','expiration')),
  source_type text,
  source_id text,
  reason text not null,
  staff_user_id uuid references public.staff_users(id) on delete set null,
  idempotency_key text unique,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  staff_user_id uuid references public.staff_users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.transactions
  add column if not exists staff_user_id uuid references public.staff_users(id) on delete set null;

alter table public.reward_redemptions
  add column if not exists staff_user_id uuid references public.staff_users(id) on delete set null;

create index if not exists staff_users_auth_user_id_idx on public.staff_users(auth_user_id);
create index if not exists points_transactions_member_created_idx on public.points_transactions(member_id, created_at desc);
create index if not exists points_transactions_staff_created_idx on public.points_transactions(staff_user_id, created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id, created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists staff_users_set_updated_at on public.staff_users;
create trigger staff_users_set_updated_at
before update on public.staff_users
for each row execute function public.set_updated_at();

create or replace function public.current_staff_user()
returns public.staff_users
language sql
stable
security definer
set search_path = public
as $$
  select s.*
  from public.staff_users s
  where s.auth_user_id = auth.uid()
    and s.is_active = true
  limit 1;
$$;

create or replace function public.is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_users
    where auth_user_id = auth.uid() and is_active = true
  );
$$;

create or replace function public.has_staff_role(p_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_users
    where auth_user_id = auth.uid()
      and is_active = true
      and role = any(p_roles)
  );
$$;

create or replace function public.award_member_points(
  p_member_code text,
  p_points bigint,
  p_reason text,
  p_idempotency_key text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  member_id bigint,
  member_name text,
  previous_balance bigint,
  new_balance bigint,
  ledger_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff public.staff_users%rowtype;
  v_member public.members%rowtype;
  v_previous bigint;
  v_ledger_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select * into v_staff
  from public.staff_users
  where auth_user_id = auth.uid()
    and is_active = true
  limit 1;

  if v_staff.id is null then
    raise exception 'Active staff account required' using errcode = '42501';
  end if;

  if p_points is null or p_points <= 0 or p_points > 100000 then
    raise exception 'Points must be between 1 and 100000' using errcode = '22023';
  end if;

  if nullif(trim(p_member_code), '') is null then
    raise exception 'Member code is required' using errcode = '22023';
  end if;

  if nullif(trim(p_reason), '') is null then
    raise exception 'Reason is required' using errcode = '22023';
  end if;

  if p_idempotency_key is not null then
    select pt.member_id, m.full_name, pt.balance_after - pt.points_delta, pt.balance_after, pt.id
      into member_id, member_name, previous_balance, new_balance, ledger_id
    from public.points_transactions pt
    join public.members m on m.id = pt.member_id
    where pt.idempotency_key = p_idempotency_key;

    if found then
      return next;
      return;
    end if;
  end if;

  select * into v_member
  from public.members
  where is_active = true
    and (
      qr_code = trim(p_member_code)
      or id::text = trim(p_member_code)
    )
  for update;

  if v_member.id is null then
    raise exception 'Active member not found' using errcode = 'P0002';
  end if;

  v_previous := coalesce(v_member.points, 0);

  update public.members
  set points = v_previous + p_points,
      lifetime_points = coalesce(lifetime_points, 0) + p_points,
      total_visits = coalesce(total_visits, 0) + 1,
      last_visit_at = now()
  where id = v_member.id;

  insert into public.points_transactions (
    member_id,
    points_delta,
    balance_after,
    transaction_type,
    source_type,
    reason,
    staff_user_id,
    idempotency_key,
    metadata
  ) values (
    v_member.id,
    p_points,
    v_previous + p_points,
    'award',
    'scanner',
    trim(p_reason),
    v_staff.id,
    p_idempotency_key,
    coalesce(p_metadata, '{}'::jsonb)
  ) returning id into v_ledger_id;

  insert into public.audit_logs (
    actor_user_id,
    staff_user_id,
    action,
    entity_type,
    entity_id,
    old_values,
    new_values,
    metadata
  ) values (
    auth.uid(),
    v_staff.id,
    'points.award',
    'member',
    v_member.id::text,
    jsonb_build_object('points', v_previous),
    jsonb_build_object('points', v_previous + p_points),
    jsonb_build_object('points_awarded', p_points, 'reason', trim(p_reason)) || coalesce(p_metadata, '{}'::jsonb)
  );

  member_id := v_member.id;
  member_name := coalesce(v_member.full_name, 'VIVID+ Member');
  previous_balance := v_previous;
  new_balance := v_previous + p_points;
  ledger_id := v_ledger_id;
  return next;
end;
$$;

alter table public.staff_users enable row level security;
alter table public.points_transactions enable row level security;
alter table public.audit_logs enable row level security;

-- Staff may read their own profile. Managers and above may read all active/inactive staff.
drop policy if exists staff_users_select_policy on public.staff_users;
create policy staff_users_select_policy
on public.staff_users for select
to authenticated
using (
  auth_user_id = auth.uid()
  or public.has_staff_role(array['manager','admin','owner'])
);

-- Ledger is readable by active staff; mutations happen only through secured functions/server flows.
drop policy if exists points_transactions_select_policy on public.points_transactions;
create policy points_transactions_select_policy
on public.points_transactions for select
to authenticated
using (public.is_active_staff());

-- Audit logs are restricted to management.
drop policy if exists audit_logs_select_policy on public.audit_logs;
create policy audit_logs_select_policy
on public.audit_logs for select
to authenticated
using (public.has_staff_role(array['manager','admin','owner']));

revoke all on function public.award_member_points(text,bigint,text,text,jsonb) from public;
grant execute on function public.award_member_points(text,bigint,text,text,jsonb) to authenticated;

commit;
