begin;

-- Create table if missing
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  badge text not null default 'MEMBER SPECIAL',
  terms text,
  start_at timestamptz,
  end_at timestamptz,
  is_published boolean not null default false,
  created_by uuid references public.staff_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- If the table already existed without these columns, add them now
alter table public.promotions
add column if not exists is_published boolean not null default false;

alter table public.promotions
add column if not exists start_at timestamptz;

alter table public.promotions
add column if not exists end_at timestamptz;

-- Ensure the index exists (depends on is_published/start_at/end_at now existing)
create index if not exists promotions_published_dates_idx
on public.promotions(is_published, start_at, end_at);

-- updated_at trigger
drop trigger if exists promotions_set_updated_at
on public.promotions;

create trigger promotions_set_updated_at
before update on public.promotions
for each row execute function public.set_updated_at();

-- RLS
alter table public.promotions enable row level security;

-- Grants (optional)
grant select
on table public.promotions
to anon, authenticated;

grant insert, update, delete
on table public.promotions
to authenticated;

-- Policies: public read
drop policy if exists promotions_public_read_policy
on public.promotions;

create policy promotions_public_read_policy
on public.promotions
for select
to anon, authenticated
using (
  is_published = true
  and (start_at is null or start_at <= now())
  and (end_at is null or end_at >= now())
);

-- Policies: staff read
drop policy if exists promotions_owner_read_policy
on public.promotions;

create policy promotions_owner_read_policy
on public.promotions
for select
to authenticated
using (
  public.has_staff_role(
    array['admin', 'owner']::text[]
  )
);

-- Insert policy for staff
drop policy if exists promotions_owner_insert_policy
on public.promotions;

create policy promotions_owner_insert_policy
on public.promotions
for insert
to authenticated
with check (
  public.has_staff_role(
    array['admin', 'owner']::text[]
  )
);

-- Update policy for staff
drop policy if exists promotions_owner_update_policy
on public.promotions;

create policy promotions_owner_update_policy
on public.promotions
for update
to authenticated
using (
  public.has_staff_role(
    array['admin', 'owner']::text[]
  )
)
with check (
  public.has_staff_role(
    array['admin', 'owner']::text[]
  )
);

-- Delete policy for staff
drop policy if exists promotions_owner_delete_policy
on public.promotions;

create policy promotions_owner_delete_policy
on public.promotions
for delete
to authenticated
using (
  public.has_staff_role(
    array['admin', 'owner']::text[]
  )
);

commit;