begin;

alter table public.members
  add column if not exists tier_updated_at timestamptz,
  add column if not exists birthday_reward_year integer,
  add column if not exists loyalty_metadata jsonb not null default '{}'::jsonb;

create table if not exists public.loyalty_tiers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_name text not null,
  rank integer not null unique,
  minimum_lifetime_points bigint not null default 0,
  minimum_visits bigint not null default 0,
  minimum_spend numeric(12,2) not null default 0,
  points_multiplier numeric(6,2) not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.loyalty_rules (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  rule_type text not null check (
    rule_type in (
      'points_multiplier',
      'bonus_points',
      'birthday_reward',
      'visit_milestone',
      'spend_milestone'
    )
  ),
  points_value bigint,
  multiplier numeric(6,2),
  minimum_visits bigint,
  minimum_spend numeric(12,2),
  day_of_week integer check (
    day_of_week is null
    or day_of_week between 0 and 6
  ),
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists loyalty_tiers_rank_idx
  on public.loyalty_tiers(rank);

create index if not exists loyalty_tiers_active_idx
  on public.loyalty_tiers(is_active);

create index if not exists loyalty_rules_active_type_idx
  on public.loyalty_rules(is_active, rule_type);

create index if not exists loyalty_rules_schedule_idx
  on public.loyalty_rules(starts_at, ends_at);

insert into public.loyalty_tiers (
  name,
  display_name,
  rank,
  minimum_lifetime_points,
  minimum_visits,
  minimum_spend,
  points_multiplier
)
values
  ('bronze', 'Bronze', 1, 0, 0, 0, 1.00),
  ('silver', 'Silver', 2, 500, 5, 250, 1.10),
  ('gold', 'Gold', 3, 1500, 15, 750, 1.25),
  ('platinum', 'Platinum', 4, 3500, 30, 1500, 1.50),
  ('diamond', 'Diamond', 5, 7500, 60, 3000, 2.00)
on conflict (name) do update
set
  display_name = excluded.display_name,
  rank = excluded.rank,
  minimum_lifetime_points = excluded.minimum_lifetime_points,
  minimum_visits = excluded.minimum_visits,
  minimum_spend = excluded.minimum_spend,
  points_multiplier = excluded.points_multiplier,
  is_active = true,
  updated_at = now();

create or replace function public.calculate_member_tier(
  p_lifetime_points bigint,
  p_total_visits bigint,
  p_total_spent numeric
)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select lt.name
      from public.loyalty_tiers lt
      where lt.is_active = true
        and coalesce(p_lifetime_points, 0) >= lt.minimum_lifetime_points
        and coalesce(p_total_visits, 0) >= lt.minimum_visits
        and coalesce(p_total_spent, 0) >= lt.minimum_spend
      order by lt.rank desc
      limit 1
    ),
    'bronze'
  );
$$;

create or replace function public.sync_member_tier()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tier text;
begin
  v_tier := public.calculate_member_tier(
    coalesce(new.lifetime_points, 0),
    coalesce(new.total_visits, 0),
    coalesce(new.total_spent, 0)
  );

  if new.membership_level is distinct from v_tier then
    new.membership_level := v_tier;
    new.tier_updated_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists members_sync_loyalty_tier
  on public.members;

create trigger members_sync_loyalty_tier
before insert or update of lifetime_points, total_visits, total_spent
on public.members
for each row
execute function public.sync_member_tier();

update public.members
set
  membership_level = public.calculate_member_tier(
    coalesce(lifetime_points, 0),
    coalesce(total_visits, 0),
    coalesce(total_spent, 0)
  ),
  tier_updated_at = now();

create or replace function public.get_member_points_multiplier(
  p_member_id bigint,
  p_at timestamptz default now()
)
returns numeric
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_tier_multiplier numeric := 1;
  v_rule_multiplier numeric := 1;
begin
  select coalesce(lt.points_multiplier, 1)
  into v_tier_multiplier
  from public.members m
  left join public.loyalty_tiers lt
    on lt.name = m.membership_level
   and lt.is_active = true
  where m.id = p_member_id;

  select coalesce(max(lr.multiplier), 1)
  into v_rule_multiplier
  from public.loyalty_rules lr
  where lr.is_active = true
    and lr.rule_type = 'points_multiplier'
    and lr.multiplier is not null
    and (
      lr.day_of_week is null
      or lr.day_of_week = extract(dow from p_at)::integer
    )
    and (
      lr.starts_at is null
      or lr.starts_at <= p_at
    )
    and (
      lr.ends_at is null
      or lr.ends_at >= p_at
    );

  return greatest(
    coalesce(v_tier_multiplier, 1),
    coalesce(v_rule_multiplier, 1)
  );
end;
$$;

create or replace function public.award_member_points(
  p_member_code text,
  p_points bigint,
  p_reason text,
  p_idempotency_key text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  member_id bigint,
  member_name text,
  previous_balance bigint,
  new_balance bigint,
  ledger_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff public.staff_users%rowtype;
  v_member public.members%rowtype;
  v_previous bigint;
  v_ledger_id bigint;
  v_multiplier numeric := 1;
  v_final_points bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required'
      using errcode = '42501';
  end if;

  select *
  into v_staff
  from public.staff_users
  where auth_user_id = auth.uid()
    and is_active = true
  limit 1;

  if v_staff.id is null then
    raise exception 'Active staff account required'
      using errcode = '42501';
  end if;

  if p_points is null
    or p_points <= 0
    or p_points > 100000 then
    raise exception 'Points must be between 1 and 100000'
      using errcode = '22023';
  end if;

  if nullif(trim(p_member_code), '') is null then
    raise exception 'Member code is required'
      using errcode = '22023';
  end if;

  if nullif(trim(p_reason), '') is null then
    raise exception 'Reason is required'
      using errcode = '22023';
  end if;

  if p_idempotency_key is not null then
    select
      pt.member_id,
      m.full_name,
      pt.balance_after - pt.points_delta,
      pt.balance_after,
      pt.id
    into
      member_id,
      member_name,
      previous_balance,
      new_balance,
      ledger_id
    from public.points_transactions pt
    join public.members m
      on m.id = pt.member_id
    where pt.idempotency_key = p_idempotency_key;

    if found then
      return next;
      return;
    end if;
  end if;

  select *
  into v_member
  from public.members
  where is_active = true
    and (
      qr_code = trim(p_member_code)
      or id::text = trim(p_member_code)
    )
  for update;

  if v_member.id is null then
    raise exception 'Active member not found'
      using errcode = 'P0002';
  end if;

  v_multiplier :=
    public.get_member_points_multiplier(v_member.id, now());

  v_final_points :=
    greatest(1, round(p_points * v_multiplier)::bigint);

  v_previous := coalesce(v_member.points, 0);

  update public.members
  set
    points = v_previous + v_final_points,
    lifetime_points =
      coalesce(lifetime_points, 0) + v_final_points,
    total_visits =
      coalesce(total_visits, 0) + 1,
    last_visit_at = now()
  where id = v_member.id;

  insert into public.points_transactions (
    member_id,
    points_delta,
    balance_after,
    transaction_type,
    source_type,
    reason,
    staff_user_id,
    idempotency_key,
    metadata
  )
  values (
    v_member.id,
    v_final_points,
    v_previous + v_final_points,
    'award',
    'loyalty_engine',
    trim(p_reason),
    v_staff.id,
    p_idempotency_key,
    coalesce(p_metadata, '{}'::jsonb)
      || jsonb_build_object(
        'base_points', p_points,
        'multiplier', v_multiplier,
        'final_points', v_final_points,
        'membership_level', v_member.membership_level
      )
  )
  returning id into v_ledger_id;

  insert into public.audit_logs (
    actor_user_id,
    staff_user_id,
    action,
    entity_type,
    entity_id,
    old_values,
    new_values,
    metadata
  )
  values (
    auth.uid(),
    v_staff.id,
    'points.award',
    'member',
    v_member.id::text,
    jsonb_build_object(
      'points',
      v_previous
    ),
    jsonb_build_object(
      'points',
      v_previous + v_final_points
    ),
    jsonb_build_object(
      'base_points',
      p_points,
      'points_awarded',
      v_final_points,
      'multiplier',
      v_multiplier,
      'reason',
      trim(p_reason)
    )
    || coalesce(p_metadata, '{}'::jsonb)
  );

  member_id := v_member.id;
  member_name :=
    coalesce(v_member.full_name, 'VIVID+ Member');
  previous_balance := v_previous;
  new_balance := v_previous + v_final_points;
  ledger_id := v_ledger_id;

  return next;
end;
$$;

alter table public.loyalty_tiers
  enable row level security;

alter table public.loyalty_rules
  enable row level security;

drop policy if exists loyalty_tiers_staff_read
  on public.loyalty_tiers;

create policy loyalty_tiers_staff_read
on public.loyalty_tiers
for select
to authenticated
using (public.is_active_staff());

drop policy if exists loyalty_tiers_owner_manage
  on public.loyalty_tiers;

create policy loyalty_tiers_owner_manage
on public.loyalty_tiers
for all
to authenticated
using (
  public.has_staff_role(
    array['admin', 'owner']
  )
)
with check (
  public.has_staff_role(
    array['admin', 'owner']
  )
);

drop policy if exists loyalty_rules_staff_read
  on public.loyalty_rules;

create policy loyalty_rules_staff_read
on public.loyalty_rules
for select
to authenticated
using (public.is_active_staff());

drop policy if exists loyalty_rules_owner_manage
  on public.loyalty_rules;

create policy loyalty_rules_owner_manage
on public.loyalty_rules
for all
to authenticated
using (
  public.has_staff_role(
    array['admin', 'owner']
  )
)
with check (
  public.has_staff_role(
    array['admin', 'owner']
  )
);

revoke all
on function public.calculate_member_tier(
  bigint,
  bigint,
  numeric
)
from public;

revoke all
on function public.get_member_points_multiplier(
  bigint,
  timestamptz
)
from public;

revoke all
on function public.award_member_points(
  text,
  bigint,
  text,
  text,
  jsonb
)
from public;

grant execute
on function public.calculate_member_tier(
  bigint,
  bigint,
  numeric
)
to authenticated;

grant execute
on function public.get_member_points_multiplier(
  bigint,
  timestamptz
)
to authenticated;

grant execute
on function public.award_member_points(
  text,
  bigint,
  text,
  text,
  jsonb
)
to authenticated;

commit;