begin;

-- =========================================================
-- VIVID+ SALES-BASED LOYALTY ENGINE
-- Staff records the final amount paid.
-- The database calculates points automatically.
-- =========================================================

create table if not exists public.member_sales (
  id bigint generated by default as identity primary key,

  member_id bigint not null
    references public.members(id)
    on delete restrict,

  staff_user_id uuid not null
    references public.staff_users(id)
    on delete restrict,

  amount_paid numeric(12,2) not null
    check (amount_paid > 0),

  payment_method text not null
    check (payment_method in ('cash', 'card')),

  tier_at_purchase text not null,

  points_per_dollar numeric(8,2) not null
    check (points_per_dollar >= 0),

  points_earned bigint not null default 0
    check (points_earned >= 0),

  previous_points_balance bigint not null default 0,
  points_balance_after bigint not null default 0,

  total_spent_before numeric(12,2) not null default 0,
  total_spent_after numeric(12,2) not null default 0,

  idempotency_key text,
  note text,

  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now()
);

create unique index if not exists member_sales_idempotency_key_idx
  on public.member_sales(idempotency_key)
  where idempotency_key is not null;

create index if not exists member_sales_member_created_idx
  on public.member_sales(member_id, created_at desc);

create index if not exists member_sales_staff_created_idx
  on public.member_sales(staff_user_id, created_at desc);

create index if not exists member_sales_created_at_idx
  on public.member_sales(created_at desc);


-- =========================================================
-- TIERS ARE NOW DETERMINED BY LIFETIME SPENDING
-- Lifetime points and visit count no longer block upgrades.
-- Existing function signature is preserved for compatibility.
-- =========================================================

create or replace function public.calculate_member_tier(
  p_lifetime_points bigint,
  p_total_visits bigint,
  p_total_spent numeric
)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select lt.name
      from public.loyalty_tiers lt
      where lt.is_active = true
        and coalesce(p_total_spent, 0) >= lt.minimum_spend
      order by lt.rank desc
      limit 1
    ),
    'bronze'
  );
$$;


-- =========================================================
-- RECORD A MEMBER SALE
--
-- Workflow:
-- 1. Staff scans member QR.
-- 2. Staff enters final amount paid.
-- 3. Database reads the member's current tier.
-- 4. Points = amount paid × tier points-per-dollar rate.
-- 5. Lifetime spending, visits and points are updated.
-- 6. Tier is recalculated automatically.
-- =========================================================

create or replace function public.record_member_sale(
  p_member_code text,
  p_amount_paid numeric,
  p_payment_method text,
  p_note text default null,
  p_idempotency_key text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  sale_id bigint,
  member_id bigint,
  member_name text,
  amount_paid numeric,
  payment_method text,
  tier_before text,
  tier_after text,
  points_per_dollar numeric,
  points_earned bigint,
  previous_points bigint,
  new_points bigint,
  previous_total_spent numeric,
  new_total_spent numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff public.staff_users%rowtype;
  v_member public.members%rowtype;

  v_sale public.member_sales%rowtype;

  v_amount numeric(12,2);
  v_payment_method text;
  v_note text;

  v_tier_before text;
  v_tier_after text;

  v_points_rate numeric(8,2) := 1;
  v_points_earned bigint := 0;

  v_previous_points bigint := 0;
  v_new_points bigint := 0;

  v_previous_total_spent numeric(12,2) := 0;
  v_new_total_spent numeric(12,2) := 0;
begin
  -- Authentication
  if auth.uid() is null then
    raise exception 'Authentication required'
      using errcode = '42501';
  end if;

  -- Active staff verification
  select *
  into v_staff
  from public.staff_users
  where auth_user_id = auth.uid()
    and is_active = true
  limit 1;

  if v_staff.id is null then
    raise exception 'Active staff account required'
      using errcode = '42501';
  end if;

  -- Member code validation
  if nullif(trim(p_member_code), '') is null then
    raise exception 'Member code is required'
      using errcode = '22023';
  end if;

  -- Sale amount validation
  if p_amount_paid is null then
    raise exception 'Amount paid is required'
      using errcode = '22023';
  end if;

  v_amount := round(p_amount_paid, 2);

  if v_amount <= 0 or v_amount > 100000 then
    raise exception 'Amount paid must be between $0.01 and $100,000'
      using errcode = '22023';
  end if;

  -- Payment method validation
  v_payment_method := lower(trim(coalesce(p_payment_method, '')));

  if v_payment_method not in ('cash', 'card') then
    raise exception 'Payment method must be cash or card'
      using errcode = '22023';
  end if;

  -- Optional note validation
  v_note := nullif(trim(coalesce(p_note, '')), '');

  if v_note is not null and length(v_note) > 250 then
    raise exception 'Note cannot exceed 250 characters'
      using errcode = '22023';
  end if;

  -- Return the original result when the same request is submitted again
  if p_idempotency_key is not null then
    select *
    into v_sale
    from public.member_sales
    where idempotency_key = trim(p_idempotency_key)
    limit 1;

    if v_sale.id is not null then
      select membership_level
      into v_tier_after
      from public.members
      where id = v_sale.member_id;

      sale_id := v_sale.id;
      member_id := v_sale.member_id;

      select coalesce(full_name, 'VIVID+ Member')
      into member_name
      from public.members
      where id = v_sale.member_id;

      amount_paid := v_sale.amount_paid;
      payment_method := v_sale.payment_method;
      tier_before := v_sale.tier_at_purchase;
      tier_after := coalesce(v_tier_after, v_sale.tier_at_purchase);
      points_per_dollar := v_sale.points_per_dollar;
      points_earned := v_sale.points_earned;
      previous_points := v_sale.previous_points_balance;
      new_points := v_sale.points_balance_after;
      previous_total_spent := v_sale.total_spent_before;
      new_total_spent := v_sale.total_spent_after;

      return next;
      return;
    end if;
  end if;

  -- Lock member during sale processing
  select *
  into v_member
  from public.members
  where is_active = true
    and (
      qr_code = trim(p_member_code)
      or id::text = trim(p_member_code)
    )
  for update;

  if v_member.id is null then
    raise exception 'Active member not found'
      using errcode = 'P0002';
  end if;

  v_tier_before := coalesce(v_member.membership_level, 'bronze');

  -- The points_multiplier column represents points earned per $1 spent
  select coalesce(lt.points_multiplier, 1)
  into v_points_rate
  from public.loyalty_tiers lt
  where lt.name = v_tier_before
    and lt.is_active = true
  limit 1;

  v_points_rate := coalesce(v_points_rate, 1);

  -- Whole points only; partial points are not issued
  v_points_earned :=
    greatest(
      0,
      floor(v_amount * v_points_rate)::bigint
    );

  v_previous_points := coalesce(v_member.points, 0);
  v_new_points := v_previous_points + v_points_earned;

  v_previous_total_spent :=
    coalesce(v_member.total_spent, 0);

  v_new_total_spent :=
    v_previous_total_spent + v_amount;

  -- Updates trigger the automatic tier recalculation
  update public.members
  set
    points = v_new_points,
    lifetime_points =
      coalesce(lifetime_points, 0) + v_points_earned,
    total_spent = v_new_total_spent,
    total_visits =
      coalesce(total_visits, 0) + 1,
    last_visit_at = now()
  where id = v_member.id
  returning membership_level
  into v_tier_after;

  -- Permanent sales ledger
  insert into public.member_sales (
    member_id,
    staff_user_id,
    amount_paid,
    payment_method,
    tier_at_purchase,
    points_per_dollar,
    points_earned,
    previous_points_balance,
    points_balance_after,
    total_spent_before,
    total_spent_after,
    idempotency_key,
    note,
    metadata
  )
  values (
    v_member.id,
    v_staff.id,
    v_amount,
    v_payment_method,
    v_tier_before,
    v_points_rate,
    v_points_earned,
    v_previous_points,
    v_new_points,
    v_previous_total_spent,
    v_new_total_spent,
    nullif(trim(coalesce(p_idempotency_key, '')), ''),
    v_note,
    coalesce(p_metadata, '{}'::jsonb)
      || jsonb_build_object(
        'request_source', 'staff_scanner',
        'tier_before', v_tier_before,
        'tier_after', coalesce(v_tier_after, v_tier_before)
      )
  )
  returning *
  into v_sale;

  -- Points ledger
  if v_points_earned > 0 then
    insert into public.points_transactions (
      member_id,
      points_delta,
      balance_after,
      transaction_type,
      source_type,
      reason,
      staff_user_id,
      idempotency_key,
      metadata
    )
    values (
      v_member.id,
      v_points_earned,
      v_new_points,
      'award',
      'member_sale',
      'Points earned from purchase',
      v_staff.id,
      case
        when p_idempotency_key is null then null
        else trim(p_idempotency_key) || ':points'
      end,
      coalesce(p_metadata, '{}'::jsonb)
        || jsonb_build_object(
          'sale_id', v_sale.id,
          'amount_paid', v_amount,
          'payment_method', v_payment_method,
          'tier_at_purchase', v_tier_before,
          'points_per_dollar', v_points_rate,
          'points_earned', v_points_earned
        )
    );
  end if;

  -- Audit history
  insert into public.audit_logs (
    actor_user_id,
    staff_user_id,
    action,
    entity_type,
    entity_id,
    old_values,
    new_values,
    metadata
  )
  values (
    auth.uid(),
    v_staff.id,
    'sale.record',
    'member_sale',
    v_sale.id::text,
    jsonb_build_object(
      'member_points', v_previous_points,
      'member_total_spent', v_previous_total_spent,
      'membership_level', v_tier_before
    ),
    jsonb_build_object(
      'member_points', v_new_points,
      'member_total_spent', v_new_total_spent,
      'membership_level', coalesce(v_tier_after, v_tier_before)
    ),
    coalesce(p_metadata, '{}'::jsonb)
      || jsonb_build_object(
        'member_id', v_member.id,
        'amount_paid', v_amount,
        'payment_method', v_payment_method,
        'points_per_dollar', v_points_rate,
        'points_earned', v_points_earned
      )
  );

  sale_id := v_sale.id;
  member_id := v_member.id;
  member_name := coalesce(v_member.full_name, 'VIVID+ Member');
  amount_paid := v_amount;
  payment_method := v_payment_method;
  tier_before := v_tier_before;
  tier_after := coalesce(v_tier_after, v_tier_before);
  points_per_dollar := v_points_rate;
  points_earned := v_points_earned;
  previous_points := v_previous_points;
  new_points := v_new_points;
  previous_total_spent := v_previous_total_spent;
  new_total_spent := v_new_total_spent;

  return next;
end;
$$;


-- =========================================================
-- ROW LEVEL SECURITY
-- Sales history is readable by active staff.
-- Sales are created only through record_member_sale().
-- =========================================================

alter table public.member_sales
  enable row level security;

drop policy if exists member_sales_staff_read
  on public.member_sales;

create policy member_sales_staff_read
on public.member_sales
for select
to authenticated
using (public.is_active_staff());


-- =========================================================
-- FUNCTION PERMISSIONS
-- =========================================================

revoke all
on function public.record_member_sale(
  text,
  numeric,
  text,
  text,
  text,
  jsonb
)
from public;

grant execute
on function public.record_member_sale(
  text,
  numeric,
  text,
  text,
  text,
  jsonb
)
to authenticated;

commit;